language:

before_install:

install:

before_script:

script:

after_success:

after_failure:

before_deploy:

deploy:

after_deploy:

git:

depth:

branches:

except:

only:

rvm:

gemfile:

env:

matrix:

exclude:

go_import_path:
